version: '3.8'

services:
  # Web Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: testflow_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
      - ./public/attachments:/var/www/html/public/attachments
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:sSCM1QNmqBBQ0kDOs6JFmHIRGIbbUJJJP6jkXH3t8ag=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=database
    depends_on:
      - redis
    networks:
      - testflow_network

  # Redis for Caching and Sessions
  redis:
    image: redis:7-alpine
    container_name: testflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - testflow_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: testflow_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - testflow_network

  # Database Backup Service
  backup:
    image: alpine:latest
    container_name: testflow_backup
    restart: unless-stopped
    volumes:
      - ./database:/data/database
      - ./backups:/data/backups
      - ./backup.sh:/backup.sh
    command: sh -c "chmod +x /backup.sh && crond -f"
    environment:
      - BACKUP_SCHEDULE=0 2 * * *  # Daily at 2 AM
    networks:
      - testflow_network

  # Monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: testflow_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    networks:
      - testflow_network

  # Grafana for Dashboards
  grafana:
    image: grafana/grafana:latest
    container_name: testflow_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    networks:
      - testflow_network

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  testflow_network:
    driver: bridge
